### ISSUE TITLE
/wish luck 找不到 up_guarantee 的值

### ISSUE THREAD

**Issue by seriaati** [seriaati/shenhe_bot#29]
```py
Traceback (most recent call last):
  File "C:\Users\alice\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\app_commands\commands.py", line 649, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "C:\Users\alice\shenhe_bot\cogs\wish.py", line 274, in wish_analysis
    get_num, use_pull, left_pull, up_guarantee = await self.char_banner_calc(
  File "C:\Users\alice\shenhe_bot\cogs\wish.py", line 180, in char_banner_calc
    return get_num, use_pull, left_pull, up_guarantee
UnboundLocalError: local variable 'up_guarantee' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\alice\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\app_commands\tree.py", line 1157, in call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\alice\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\app_commands\commands.py", line 675, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\alice\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\app_commands\commands.py", line 668, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'luck歐氣值' raised an exception: UnboundLocalError: local variable 'up_guarantee' referenced before assignment 
```

**Comment by seriaati** [comment]
fixed in https://github.com/seriaati/shenhe_bot/commit/f90499b7a796275d5ca5f8420fda9e380567af16
